name: superpower
version: 0.1.0
author: Simon Leier <simonleier@gmail.com>
description: "Lists and Iterables on steroids! 🦄"
homepage: https://github.com/leisim/superpower
environment:
  sdk: '>=2.0.0-dev.60.0 <3.0.0'
dependencies:
  collection: '>=1.14.0 <1.15.0'
dev_dependencies:
  test: any
  grinder: ^0.8.3
  dartdoc: ^0.20.3
