name: superpower
version: 0.3.0
author: Simon Leier <simonleier@gmail.com>
description: "Lists, Iterables and Maps on steroids! 🦄 Extends Lists with negative indices, sortedBy(), groupBy(), distinct(), slice(), flatten() etc. Inspired by Kotlin."
homepage: https://github.com/leisim/superpower
environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'
dependencies:
  collection: '>=1.14.11 <1.15.0'
dev_dependencies:
  test: any
  grinder: ^0.8.3
